{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stzteam.features.limelight",
    "module": "MARSLimelightFeature",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MARSLimelightFeature-1.0.0.jar",
          "url": "MARSLimelightFeature-1.0.0.jar",
          "size": 28485,
          "sha512": "5d856bd2aff5c68009948ff55bcc1b3b342cce16c104fb2f89f3a63d392fdd646a1e003247c663f24cd87e5a59ec6c7e00d21d2c73d5d47acc46bf71356e329f",
          "sha256": "9f364fb3dc992aa72bd3c1b3548ba6593590ce3493350beeb80340146b89d990",
          "sha1": "4b159dfc474883f0d79cd152c47bfcebaeb1fbd7",
          "md5": "679f08e8044fa3f77af841630f59a76a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.stzteam.forgemini",
          "module": "ForgeMini",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.stzteam.mars",
          "module": "Mars",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "MARSLimelightFeature-1.0.0.jar",
          "url": "MARSLimelightFeature-1.0.0.jar",
          "size": 28485,
          "sha512": "5d856bd2aff5c68009948ff55bcc1b3b342cce16c104fb2f89f3a63d392fdd646a1e003247c663f24cd87e5a59ec6c7e00d21d2c73d5d47acc46bf71356e329f",
          "sha256": "9f364fb3dc992aa72bd3c1b3548ba6593590ce3493350beeb80340146b89d990",
          "sha1": "4b159dfc474883f0d79cd152c47bfcebaeb1fbd7",
          "md5": "679f08e8044fa3f77af841630f59a76a"
        }
      ]
    }
  ]
}
